/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author MaC
 */
public class patientRecords extends javax.swing.JFrame {

    /**
     * Creates new form patientRecords
     */
    int xMouse;
    int yMouse;
    public patientRecords() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        //setExtendedState(home.MAXIMIZED_BOTH);
        //jLabel1.setIcon(new ImageIcon(new ImageIcon("/img/logo.png").getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MoveBar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        txtPID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDOB = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtMNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDrugAllergies = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCurrentMed = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMedHistory = new javax.swing.JTextArea();
        txtSearch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnClear = new keeptoo.KButton();
        btnSearch = new keeptoo.KButton();
        btnAdd = new keeptoo.KButton();
        btnView = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        btnSave = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(25);
        kGradientPanel1.setkEndColor(new java.awt.Color(76, 161, 175));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(44, 62, 80));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 0, 29, 30));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1297, 0, 28, 30));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Records");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        MoveBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoveBarMouseDragged(evt);
            }
        });
        MoveBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoveBarMousePressed(evt);
            }
        });
        kGradientPanel1.add(MoveBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 0, 930, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-fever-80.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        kGradientPanel2.setkBorderRadius(25);
        kGradientPanel2.setkEndColor(new java.awt.Color(76, 161, 175));
        kGradientPanel2.setkGradientFocus(600);
        kGradientPanel2.setkStartColor(new java.awt.Color(44, 62, 80));
        kGradientPanel2.setOpaque(false);

        kGradientPanel3.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkBorderRadius(25);
        kGradientPanel3.setkEndColor(new java.awt.Color(240, 240, 240));
        kGradientPanel3.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel3.setOpaque(false);
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIDActionPerformed(evt);
            }
        });
        txtPID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPIDKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 89, 193, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setText("Patient's ID");
        kGradientPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 93, 136, -1));

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        txtFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullNameKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 137, 396, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setText("Full Name");
        kGradientPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 141, 136, -1));

        txtDOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel3.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 185, 199, 28));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setText("DOB");
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 185, 136, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 231, 408, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        kGradientPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 296, 136, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel8.setText("ID Number");
        kGradientPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 235, 136, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        kGradientPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 288, 302, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel9.setText("Country");
        kGradientPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 416, 136, -1));

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        txtCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCountryKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 412, 196, 30));

        txtMNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNumberActionPerformed(evt);
            }
        });
        txtMNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMNumberKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtMNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 460, 196, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel10.setText("Mobile Number");
        kGradientPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 464, 136, -1));

        txtTNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTNumberActionPerformed(evt);
            }
        });
        txtTNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTNumberKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtTNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 508, 196, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel11.setText("Tel. Number");
        kGradientPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 512, 136, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 556, 196, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel12.setText("Email");
        kGradientPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 560, 136, -1));

        txtDrugAllergies.setColumns(20);
        txtDrugAllergies.setRows(5);
        jScrollPane2.setViewportView(txtDrugAllergies);

        kGradientPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 318, 464, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel13.setText("Drug Allergies");
        kGradientPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 288, 130, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel14.setText("Current Medicine");
        kGradientPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 446, 135, -1));

        txtCurrentMed.setColumns(20);
        txtCurrentMed.setRows(5);
        jScrollPane3.setViewportView(txtCurrentMed);

        kGradientPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 476, 464, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel15.setText("Medical History");
        kGradientPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 603, 139, -1));

        txtMedHistory.setColumns(20);
        txtMedHistory.setRows(5);
        jScrollPane4.setViewportView(txtMedHistory);

        kGradientPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 633, 464, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 89, 237, 30));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel16.setText("Patient");
        kGradientPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 93, 67, -1));

        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnClear.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 743, 167, -1));

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSearch.setkAllowGradient(false);
        btnSearch.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnSearch.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 84, 146, 35));

        btnAdd.setText("Add Patient");
        btnAdd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnAdd.setkAllowGradient(false);
        btnAdd.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnAdd.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 671, 167, -1));

        btnView.setText("View Booking");
        btnView.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnView.setkAllowGradient(false);
        btnView.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnView.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnView.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 743, 167, -1));

        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnDelete.setkAllowGradient(false);
        btnDelete.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnDelete.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 743, 167, -1));

        btnSave.setText("Save Patient");
        btnSave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSave.setkAllowGradient(false);
        btnSave.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnSave.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnSave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 671, 167, -1));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 836));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MoveBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_MoveBarMousePressed

    private void MoveBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse-360, y - yMouse);
    }//GEN-LAST:event_MoveBarMouseDragged

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        //login log = new login();
        this.setState(patientRecords.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void txtPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPIDActionPerformed

    private void txtPIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPIDKeyReleased

        /*if(v_ID.getText().isEmpty()){JOptionPane.showMessageDialog(null, "Text Box Can't be Empty!");}
        else {
            String id=  v_ID.getText();
            String sql = "SELECT vp_id , req_time FROM v_permission WHERE vp_id LIKE '%"+id+"%'";

            try {
                preSt=con.prepareStatement(sql);

                String time = null ;

                rest = preSt.executeQuery(sql);
                while(rest.next())
                {

                    double x = rest.getDouble("req_time");
                    time = Double.toString(x);
                }

                v_id_time.setText(String.valueOf(time));

                //

                //ImageIcon img;
                //img = new ImageIcon("C:\\Users\\USER\\Downloads\\c.gif");
                JOptionPane.showMessageDialog(null,time ,"VEHICLE PREMISSION",JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException ex) {
                Logger.getLogger(trip.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        */
    }//GEN-LAST:event_txtPIDKeyReleased

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtFullNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameKeyReleased

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyReleased

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryKeyReleased

    private void txtMNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNumberActionPerformed

    private void txtMNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMNumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNumberKeyReleased

    private void txtTNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTNumberActionPerformed

    private void txtTNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTNumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTNumberKeyReleased

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MoveBar;
    private keeptoo.KButton btnAdd;
    private keeptoo.KButton btnClear;
    private javax.swing.JLabel btnClose;
    private keeptoo.KButton btnDelete;
    private javax.swing.JLabel btnMinimize;
    private keeptoo.KButton btnSave;
    private keeptoo.KButton btnSearch;
    private keeptoo.KButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextArea txtCurrentMed;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextArea txtDrugAllergies;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMNumber;
    private javax.swing.JTextArea txtMedHistory;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTNumber;
    // End of variables declaration//GEN-END:variables
}
